{
 "title": "Miner stat",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Placeholder",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# This is mining stats from Hiveos workers\n\n         "
   }
  },
  {
   "title": "current mining coin price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coin_price{coin=~\"...*\"}",
     "legendFormat": "{{coin}}"
    }
   ]
  },
  {
   "title": "clean profit per week",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 3 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    { "expr": "clear_profitline_hourly*168", "legendFormat": "{{worker_name}} | {{coin}}" }
   ]
  },
  {
   "title": "hashrate by worker\\algo",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KHs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "worker_hashrate", "legendFormat": "{{worker_name}} | {{algo}}" }
   ]
  },
  {
   "title": "clean profit daily",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 7, "y": 11 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    { "expr": "clear_profitline_hourly*24", "legendFormat": "{{worker_name}} | {{coin}}" }
   ]
  },
  {
   "title": "clean profit per hour",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    { "expr": "clear_profitline_hourly", "legendFormat": "{{worker_name}} | {{coin}}" }
   ]
  }
 ]
}